# =============================================================================
# This code reads output generated by 01_AirSea_diagnostics.csh 
# from several different models or experiments.
#
# It plots mean fields in a single column using uniform contour intervals.
#
# The model cases can be arranged any way the user choses, but it is envisioned
# that the first case be either OBS/reanalysis, or a control run.  Subsequent
# cases would then be results from different models or experiments. 
#
# Environmental variable "modelname" must match one of those listed in
# airsea_definitions_DB.sh
#
# A maximum of 8 panels is allowed.  For more panels, see 
#	AirSea_MultiModel_Plot_2col.sh OR
#	AirSea_MultiModel_Plot_2col_plusOne.sh
#
# The user specifies the output directory with the "setenv dirp" commend, below
# =============================================================================

#----- user input
setenv	FilePrefix		"CGCM"	# can be "", "AGCM", "Nino", "Nina", etc.
setenv 	nCases			5		# requires one block per case, below
setenv	nRows			8		# max = 8; recommend nRows = 8 even if nCases < 8
#setenv	dirp			"/Users/demott/Projects/Coup_Uncoup/"		
setenv	dirp			"/Users/demott/Dropbox/Work/"		
setenv	panelLabStrt	0		# adjust panel labeling:  0=a, 1=b, 2=c, etc.
setenv	ColumnTitle		False	# to enable or suppress column title
setenv	PTYPE			png		# png or pdf
setenv	u850_overlay	"true"	# add U850>0 contours
setenv	DEBUG 			"false"	# "false" suppresses non-fatal NCL warning messages

#----- font sizes for column labels, color bars, panel labels.
#	   these can be adjusted if desired, but have been 
#	   adjusted to produce "appropriate" font sizes for
#      panel sizes (RESULTS WILL APPEAR DIFFERENT IF NOT nRows = 8!!!)
setenv	AxisFontHt		0.019
setenv	TitleFontHt		0.012
setenv	PanelFontHt		0.010
setenv	LabelBarFontHt	0.007


set	ExtraVars	= "false"
if ($ExtraVars == "false") then
	setenv ExtraVarList	"( PW )"
endif

#----- case 0 ; 0-based indexing 
setenv 	modelname ERAI
source 	./AirSea_definitions.sh # handle model-specific logic
setenv	caseName0	$modelname
setenv 	MODDIR0		$FILEDIR
setenv 	MODNAME0	$modelname
setenv	MODDATES0	$YMDSTRT"-"$YMDLAST

#----- case 1
setenv 	modelname SPCCSM
source 	./AirSea_definitions.sh # handle model-specific logic
setenv	caseName1	$modelname
setenv 	MODDIR1		$FILEDIR
setenv 	MODNAME1	$modelname
setenv	MODDATES1	$YMDSTRT"-"$YMDLAST

#----- case 2
setenv 	modelname MetUM-GOML
source 	./AirSea_definitions.sh # handle model-specific logic
setenv	caseName2	$modelname
setenv 	MODDIR2		$FILEDIR
setenv 	MODNAME2	$modelname
setenv	MODDATES2	$YMDSTRT"-"$YMDLAST

#----- case 3
setenv 	modelname ECHAM-CPL
source 	./AirSea_definitions.sh # handle model-specific logic
setenv	caseName3	$modelname
setenv 	MODDIR3		$FILEDIR
setenv 	MODNAME3	$modelname
setenv	MODDATES3	$YMDSTRT"-"$YMDLAST

#----- case 4
setenv 	modelname CNRM-CM
source 	./AirSea_definitions.sh # handle model-specific logic
setenv	caseName4	$modelname
setenv 	MODDIR4		$FILEDIR
setenv 	MODNAME4	$modelname
setenv	MODDATES4	$YMDSTRT"-"$YMDLAST

#============= LEVEL 1 DIAGNOSTICS:  MEAN, STDEV, RH-SST-WIND PDFs
set Plot_Means					= "false"		# plot_MultiModel_Means_1col.ncl
set Plot_StDevs					= "false"		# plot_MultiModel_StDev_1col.ncl
set Plot_SST_skewness			= "false"		# plot_MultiModel_SSTskewness_1col.ncl
set Plot_RH_byWindSST			= "false"		# plot_MultiModel_RH_byWindSST_1col.ncl

#============= LEVEL 2 DIAGNOSTICS:  LAG REGRESSIONS, WHEELER-KILADIS PLOTS
set Plot_RainHov_Regressions	= "false"		# plot_MultiModel_RainHovs_1col.ncl
set Plot_BasePoint_Regressions	= "false"		# plot_MultiModel_BasePoint_regressions_1col.ncl

#============= LEVEL 3 DIAGNOSTICS:  LAG=0 MSE, dMSE/dT, dSST/dt REGRESSION MAPS
set Plot_MSE_Regressions		= "false"		# plot_MultiModel_MSEbudget_regressions_1col.ncl
set Plot_SST_Effect				= "true"		# plot_MultiModel_SST_Effect_1col.ncl

#========================= LEVEL 1 COMPARISON PLOTS =======================
#--------------------------------------------------------------------------
#  SEASONAL MEANS 
if ($Plot_Means == "true") then
	foreach inName ( PRECT SPD LHFLX SHFLX SST RHsfc Qair Qsat delQ Qnet)
		setenv varName $inName
		ncl -Q ./CompareMultiple/plot_MultiModel_Means_1col.ncl
	end
	
	if ($ExtraVars == "true") then
		foreach inName $ExtraVarList
			setenv varName $inName
			ncl -Q ./CompareMultiple/plot_MultiModel_Means_1col.ncl
		end
	endif
endif

#--------------------------------------------------------------------------
#  SEASONAL STDEVS 
if ($Plot_StDevs == "true") then
	foreach inName ( PRECT SPD LHFLX SHFLX SST RHsfc Qair Qsat delQ Qnet SWsfc )
		setenv varName $inName
		ncl -Q ./CompareMultiple/plot_MultiModel_StDevs_1col.ncl
	end
	
	if ($ExtraVars == "true") then
		foreach inName $ExtraVarList
			setenv varName $inName
			ncl -Q ./CompareMultiple/plot_MultiModel_StDevs_1col.ncl
		end
	endif
endif

#--------------------------------------------------------------------------
#  MSE budget terms projections 
if ($Plot_MSE_Regressions == "true") then
	setenv baseVar Vmse
	#foreach inName ( Vm_hadv Vudmdx Vvdmdy Vomegadmdp Vlw Vsw LHFLX SHFLX )
	foreach inName ( Vm_hadv  )
		setenv varName $inName
		ncl -Q ./CompareMultiple/plot_MultiModel_MSEbudget_regressions_1col.ncl
	end
	
# 	setenv baseVar Vdmdt
# 	foreach inName ( Vm_hadv Vudmdx Vvdmdy Vomegadmdp Vlw Vsw LHFLX SHFLX )
# 		setenv varName $inName
# 		ncl -Q ./CompareMultiple/plot_MultiModel_MSEbudget_regressions_1col.ncl
# 	end
# 
# 	if ($ExtraVars == "true") then
# 		setenv baseVar Vmse
# 		foreach inName $ExtraVarList
# 			setenv varName $inName
# 			ncl -Q ./CompareMultiple/plot_MultiModel_MSEbudget_regressions_1col.ncl
# 		end
# 
# 		setenv baseVar Vdmdt
# 		foreach inName $ExtraVarList
# 			setenv varName $inName
# 			ncl -Q ./CompareMultiple/plot_MultiModel_MSEbudget_regressions_1col.ncl
# 		end
# 	endif
endif

#--------------------------------------------------------------------------
#  SST skewness 
if ($Plot_SST_skewness == "true") then
	ncl -Q ./CompareMultiple/plot_MultiModel_SSTskewness_1col.ncl
endif

#--------------------------------------------------------------------------
#	RH_by WindSST_PDFs
if ($Plot_RH_byWindSST == "true") then
	ncl -Q ./CompareMultiple/plot_MultiModel_RH_byWindSST_PDF_1col.ncl
endif


#========================= LEVEL 2 COMPARISON PLOTS =======================
#--------------------------------------------------------------------------

#  RAIN HOVMOLLLER REGRESSSIONS
if ($Plot_RainHov_Regressions == "true") then
	setenv varName PRECT
	ncl -Q ./CompareMultiple/plot_MultiModel_RainHovs_1col.ncl
endif

#  BASE POINT REGRESSIONS 
if ($Plot_BasePoint_Regressions == "true") then
	foreach inName ( PRECT SST Vmse Vdmdt Vm_hadv Vudmdx Vvdmdy Vlw Vsw LHFLX SHFLX U850 Qair delQ Tair delT )
		setenv baseVar PRECT
		setenv varName $inName
		ncl -Q ./CompareMultiple/plot_MultiModel_BasePointRegressions_1col.ncl
	end

	if ($ExtraVars == "true") then
		foreach inName $ExtraVarList
			setenv baseVar PRECT
			setenv varName $inName
			ncl -Q ./CompareMultiple/plot_MultiModel_BasePointRegressions_1col.ncl
		end
	endif
endif


