#!/bin/csh

# =============================================================================
# This code reads output generated by airsea_diagnostics_DB.csh as applied
# to several different models or experiments.
#
# It plots "observations" plus model mean fields in two columns using uniform contour intervals.
#
# A maximum of 8 panels is allowed.  For more panels, see 
#	AirSea_MultiModel_Plot_Means_2col.sh
#
# The model cases can be arranged any way the user choses, but it is envisioned
# that the first case be either OBS/reanalysis, or a control run.  Subsequent
# cases would then be results from different models or experiments.  For example,
# the left (right) column could be coupled (uncoupled) simulations.
#
# Environmental variable "modelname" must match one of those listed in
# airsea_definitions_DB.sh
#
# The user specifies the output directory with the "setenv dirp" command
# =============================================================================

setenv 	nCases			9		# requires one block per case, below
#setenv	dirp			"/Users/demott/Projects/Coup_UnCoup/"		
setenv	dirp			"/Users/demott/Dropbox/Work/"		
setenv	panelLabStrt	0		# adjust panel labeling:  0=a, 1=b, 2=c, etc.

foreach var	( PRECT )

	setenv varName $var

	#----- case 0 ; 0-based indexing used in NCL, so we'll stick with that
	setenv 	modelname ERAI
	#echo 	$modelname
	source 	../airsea_definitions_DB.sh # handle model-specific logic
	setenv	caseName0	$modelname
	setenv 	MODDIR0		$FILEDIR
	setenv 	MODNAME0	$modelname
	setenv	MODDATES0	$YMDSTRT"-"$YMDLAST
	echo $MODDATES0
	
	#----- case 1
	setenv 	modelname CAM4-ctrl
	#echo 	$modelname
	source 	../airsea_definitions_DB.sh # handle model-specific logic
	setenv	caseName1	$modelname
	setenv 	MODDIR1		$FILEDIR
	setenv 	MODNAME1	$modelname
	setenv	MODDATES1	$YMDSTRT"-"$YMDLAST
	
	#----- case 2
	setenv 	modelname SPCAM4-ctrl
	#echo 	$modelname
	source 	../airsea_definitions_DB.sh # handle model-specific logic
	setenv	caseName2	$modelname
	setenv 	MODDIR2		$FILEDIR
	setenv 	MODNAME2	$modelname
	setenv	MODDATES2	$YMDSTRT"-"$YMDLAST
	
	#----- case 3
	setenv 	modelname CAM4-flatisland
	#echo 	$modelname
	source 	../airsea_definitions_DB.sh # handle model-specific logic
	setenv	caseName3	$modelname
	setenv 	MODDIR3		$FILEDIR
	setenv 	MODNAME3	$modelname
	setenv	MODDATES3	$YMDSTRT"-"$YMDLAST
	
	#----- case 4
	setenv 	modelname SPCAM4-flatisland
	#echo 	$modelname
	source 	../airsea_definitions_DB.sh # handle model-specific logic
	setenv	caseName4	$modelname
	setenv 	MODDIR4		$FILEDIR
	setenv 	MODNAME4	$modelname
	setenv	MODDATES4	$YMDSTRT"-"$YMDLAST
	
	#----- case 5
	setenv 	modelname CAM4-noland
	#echo 	$modelname
	source 	../airsea_definitions_DB.sh # handle model-specific logic
	setenv	caseName5	$modelname
	setenv 	MODDIR5		$FILEDIR
	setenv 	MODNAME5	$modelname
	setenv	MODDATES5	$YMDSTRT"-"$YMDLAST
	
	#----- case 6
	setenv 	modelname SPCAM4-noland
	#echo 	$modelname
	source 	../airsea_definitions_DB.sh # handle model-specific logic
	setenv	caseName6	$modelname
	setenv 	MODDIR6		$FILEDIR
	setenv 	MODNAME6	$modelname
	setenv	MODDATES6	$YMDSTRT"-"$YMDLAST
	
	#----- case 7
	setenv 	modelname CAM4-nodc-landfrac30
	#echo 	$modelname
	source 	../airsea_definitions_DB.sh # handle model-specific logic
	setenv	caseName7	$modelname
	setenv 	MODDIR7		$FILEDIR
	setenv 	MODNAME7	$modelname
	setenv	MODDATES7	$YMDSTRT"-"$YMDLAST
	
	#----- case 8
	setenv 	modelname SPCAM4-nodc-landfrac30
	#echo 	$modelname
	source 	../airsea_definitions_DB.sh # handle model-specific logic
	setenv	caseName8	$modelname
	setenv 	MODDIR8		$FILEDIR
	setenv 	MODNAME8	$modelname
	setenv	MODDATES8	$YMDSTRT"-"$YMDLAST
	
	ncl -Q ./plot_MultiModel_RainHovs_2col_plusOne.ncl

end

