#!/bin/csh

# #		fixme: see if some of the regression steps (e.g., make_L1.4...) can be distributed across
# #				multiple processors, if available

#foreach modelname ("ECHAM-A31" "ERAI" "MetUM-GOML" "MetUM-ACM" "SPCCSM" "SPCAM_5d" "CNRM-CM" "CNRM-ACM" )
foreach modelname ( "SPCAM3_mon" )
#foreach modelname ("ECHAM-A31" )
	echo $modelname
	source ./Diagnostics_V4/airsea_definitions_DB.sh # handle model-specific logic

	setenv 	CDIR	$FILEDIR/proc/
	setenv 	CNAME	$modelname
	setenv	CDATES	$YMDSTRT"-"$YMDLAST

	#============= Level 3 difference files ==================
	foreach pName ("make_L3.1_regression_map" )
		echo "Processing output generated by " $pName
		foreach cFile ($CDIR$CNAME.*.$pName.*.nc)
			#echo $cFile
			# parse variable names and season from input file
			set season	=	`echo $cFile | cut -d . -f2`
			set dRange	=	`echo $cFile | cut -d . -f5`
			set var1	= 	`echo $cFile | cut -d . -f6`
			set var2	=	`echo $cFile | cut -d . -f7`
			#echo $CDIR$CNAME.$pName.$dRange.$var1.$var2.$season.nc
			mv $cFile $CDIR$CNAME.$pName.$dRange.$var1.$var2.$season.nc
 		end
	end
	echo " "

	foreach pName ("make_L3.2_MSE_PDF_lineplots")
		#ls $CDIR$CNAME*$pName*.nc
		foreach cFile ($CDIR$CNAME*$pName*.nc)
			#echo $cFile
			set season	=	`echo $cFile | cut -d . -f2`
			set dRange	=	`echo $cFile | cut -d . -f5`
			set latRange =	`echo $cFile | cut -d . -f6`
			set lonRange =	`echo $cFile | cut -d . -f7`
			#echo $CDIR$CNAME.$pName.$latRange.$lonRange.$dRange.$season.nc
			mv $cFile $CDIR$CNAME.$pName.$latRange.$lonRange.$dRange.$season.nc
		end
	end

	foreach pName ("make_L3.3_MSE_ModProjectionMaps" )
		echo "Processing output generated by " $pName
 		foreach cFile ($CDIR$CNAME.*.$pName.*.nc)
 			#echo $cFile
			# parse variable names and season from input file
			set season	=	`echo $cFile | cut -d . -f2`
			set dRange	=	`echo $cFile | cut -d . -f5`
			#echo $CDIR$CNAME.$pName.$dRange.$season.nc
			mv $cFile $CDIR$CNAME.$pName.$dRange.$season.nc
 		end
	end
	echo " "
	echo " "
 end